### PR TITLE
ICPC-000-css-responsiveness

### PR DESCRIPTION
**Pull request by josephmilla**
@25cf, I broke the calendar. I'll fix it later.

### CODE REVIEW

**Comment by wackytobaccy** [comment]
Hi Joseph. Thanks for the pull request.

Some notes about open source style:
- Please don't make multiple issues for your own branch. Instead, just list issues with your branch in this issue.
- When making a pull request, try to rebase and squash commits so only relevant changes show up in diffs. This makes the review process much faster.
- Don't make pull requests until you're actually ready for your code to be pulled immediately. This helps avoid false backlog.

I'm withholding most of my comments on your changes until you are ready for a pull. But here are some notes on a preliminary glance:
- Remember that Bootstrap won't be used, though I see you've included it in this pull. Most of the CSS has already been written, so there's no need for that. This is a small website which would not utilize most of Bootstrap's components.
- I expected this pull to be just a few `@media` rules in the CSS... however, I don't _actually_ see any responsiveness in the CSS. I'm assuming this is because you've included Bootstrap. Please fix this ASAP, or else it seems you're missing the target.
- Like I said in the other issue, we shouldn't diverge from the spec. We should create the site as Uttam asked, then, once that is up and running, we can suggest changes.
  - In particular, I'm referring to merging Announcements and Practices, and adding an HTML footer.
  - This also applies to the Carousel on the front page. The hero image that was there before was simply a placeholder, as is most of the color/fonts/etc. Please don't focus on look and feel until we get responsiveness and a few other basics.
- Jekyll gets the date and title of posts from the file name. There's no need for an extra YAML field.
- You removed the container div from the default layout and added them to every page that uses the default layout. This seems to go against DRY.
- The calendar CSS and JavaScript should only be included on the Calendar page like it was before, to optimize load.

I will add more comments once I run your branch when I'm off from work. Please focus on adding responsiveness to the already existing CSS instead of burdening the site with Bootstrap. Thanks!

**Comment by josephmilla** [comment]
Hi Charles. Thanks for your comments!

Here are some issues:
- I would disagree with you for not using Bootstrap in this project. We're still in the "infancy" stage of the project that's why it's easy to say that most of Bootstrap components won't be utilized. Yes, I understand that this is a small website but we don't know yet what other features would be added in the near future (PC^2 web client, SPOJ training, etc.) that would be easier to implement with Bootstrap.
- I didn't write the CSS `@media` rules for the viewports because again, it would be easier to handle the different viewports using Bootstrap.
- Regarding Announcements and Practices, I just thought it would be nice to merge them in one page and just put a label on each post. However, if Uttam and Yong wanted them to be separate then keep them separate.

PS:
I'm currently in talks with Yong and Uttam.

**Comment by wackytobaccy** [comment]
Hey Joseph. I'm very glad you brought that up.

My gripe with using Bootstrap for this project is that this site is not a web application. Rather, it is a simple static website that doesn't need 99.9% of Bootstrap's components. When will we ever need dialogue boxes or tooltips on this website? Probably never - and even so, it would be smarter to nitpick what little we need and build that rather than import the entirety of Bootstrap but only use one or two of its features.

I'm not too sure about what future features you're talking about. Uttam said he was working on a tool similar to SPOJ, but I haven't heard about any recent progress on that, and that sounded like more of a long-term project. More importantly, it wasn't mentioned in the spec that Uttam wrote up. But even so, I don't see how using Bootstrap is better than writing a minimal CSS file for that tool. Bootstrap is great for rapid development of SPAs or even large web apps, but even then most people acknowledge that it's best practice to move away from Bootstrap over time to avoid the hackneyed "typical startup website" look. Regardless, this is a simple static website which will probably never utilize any of Bootstrap's most useful features. It's best to keep it simple and avoid unnecessary overhead.

If Yong and Uttam think using Bootstrap is better, or if there are some features in the future that will utilize Bootstrap fully, I'd be happy to concede. I mulled this over at the start of the project and decided against Bootstrap because I thought it would be overkill for this project, but you're welcome to prove me wrong with some ideas, although it is quite late to do that.

**Comment by yuting-zhang** [comment]
This branch is too old. Close it now.

**Pull request closed without merging**
